version: '2'
services:
  eurekaserver:
    image: bhhan87/study-eurekaserver:v1.0.0
    ports:
      - "8761:8761"
    environment:
      PORT: "8761"
  configserver:
    image: bhhan87/study-configserver:v1.0.0
    ports:
      - "8888:8888"
    environment:
      EUREKA_SERVER_PORT: "8761"
      PORT: "8888"
      CONFIG_SERVER_GIT_URI: "https://github.com/bhhan5274/study-repo.git"
      CONFIG_SERVER_GIT_SEARCH_PATHS: "order,shipping"
      CONFIG_SERVER_USERNAME: "username"
      CONFIG_SERVER_PASSWORD: "password"
  order:
    image: bhhan87/study-order:v1.0.0
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
  shipping:
    image: bhhan87/study-shipping:v1.0.0
    ports:
      - "9001:9001"
    environment:
      PORT: "9001"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
  gateway:
    image: bhhan87/study-gateway:v1.0.0
    ports:
      - "5555:5555"
    environment:
      PORT: "5555"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
