version: '2'
services:
  eurekaserver:
    image: bhhan87/study-eurekaserver:v1.0.0
    ports:
      - "8761:8761"
    environment:
      PORT: "8761"
  configserver:
    image: bhhan87/study-configserver:v1.0.0
    ports:
      - "8888:8888"
    environment:
      EUREKA_SERVER_PORT: "8761"
      PORT: "8888"
      CONFIG_SERVER_GIT_URI: "https://github.com/bhhan5274/study-repo.git"
      CONFIG_SERVER_GIT_SEARCH_PATHS: "order,shipping,gateway"
      CONFIG_SERVER_USERNAME: "username"
      CONFIG_SERVER_PASSWORD: "password"
  gateway:
    image: bhhan87/study-gateway:v1.0.0
    ports:
      - "5555:5555"
    environment:
      PORT: "5555"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
      ZIPKIN_BASE_URI: "http://zipkin:9411"
  oauth2:
    image: bhhan87/study-oauth2server:v1.0.0
    ports:
      - "8090:8090"
    environment:
      PORT: "8090"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
      POSTGRES_URI: "jdbc:postgresql://postgres:5432/sonar"
  order:
    image: bhhan87/study-order:v1.1.0
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
      KAFKA_BROKER_URI: "kafkaserver:9092"
      ZIPKIN_BASE_URI: "http://zipkin:9411"
  shipping:
    image: bhhan87/study-shipping:v1.1.0
    ports:
      - "9001:9001"
    environment:
      PORT: "9001"
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://configserver:8888"
      CONFIG_SERVER_PORT: "8888"
      KAFKA_BROKER_URI: "kafkaserver:9092"
      ZIPKIN_BASE_URI: "http://zipkin:9411"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafkaserver:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafkaserver
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs2.papertrailapp.com:42847
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
